---
# Per environment values which override defaults in hmpps-welcome-people-into-prison-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: welcome-dev.prison.service.justice.gov.uk

  allowlist: false

  env:
    INGRESS_URL: "https://welcome-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    WELCOME_API_URL: "https://welcome-api-dev.prison.service.justice.gov.uk"
    HMPPS_COOKIE_NAME: hmpps-session-dev
    APP_HOSTNAME: welcome-dev.prison.service.justice.gov.uk
    SYSTEM_PHASE: DEV
    ENABLED_PRISONS: 'NMI,MDI,LII'
    CONFIRM_ENABLED: 'true'
    CONFIRM_NO_IDENTIFIERS_ENABLED: 'true'
    TEMPORARY_ABSENCE_ENABLED: 'true'
    PRISON_TRANSFERS_ENABLED: 'true'

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
